# Generated by Django 3.0.6 on 2020-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='time',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='username',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
