# Generated by Django 3.0.6 on 2020-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200616_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
