# Generated by Django 3.0.6 on 2020-06-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200616_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
